2023-11-01 16:43:14,168 [MainThread  ] [INFO ]  Logger Started
2023-11-01 16:43:14,182 [MainThread  ] [INFO ]  Scheduler started
2023-11-01 16:43:14,199 [MainThread  ] [INFO ]  Logger Started
2023-11-01 16:43:14,200 [MainThread  ] [INFO ]  Scheduler started
2023-11-01 16:43:14,203 [MainThread  ] [INFO ]  gmonster_desktop_id - e86e379f-5918-412f-b903-d11e6a1b7c20
2023-11-01 16:43:14,211 [MainThread  ] [INFO ]  config updated
2023-11-01 16:43:15,510 [MainThread  ] [INFO ]  auto_fire_responses_webhook Interval: 1 hour
2023-11-01 16:43:15,510 [MainThread  ] [INFO ]  auto_fire_responses_webhook timer started
2023-11-01 16:43:16,361 [Thread-1    ] [INFO ]  13582
2023-11-01 16:48:16,900 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 16:48:16,911 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 16:53:17,730 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 16:53:17,731 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 16:58:19,844 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 16:58:19,845 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:03:20,664 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:03:20,665 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:08:21,505 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:08:21,505 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:13:22,364 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:13:22,365 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:18:23,202 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:18:23,203 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:23:24,038 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:23:24,039 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:28:24,880 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:28:24,881 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:33:25,715 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:33:25,716 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:38:26,560 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:38:26,560 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:43:15,506 [Thread-5    ] [INFO ]  auto_fire_responses_webhook started
2023-11-01 17:43:15,512 [SendReport_I] [INFO ]  Inbox Webhook Thread Started...
2023-11-01 17:43:17,154 [Thread-1    ] [INFO ]  13582
2023-11-01 17:43:17,899 [lithbello60@] [ERROR]  Error at downloading email - lithbello60@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 17:43:18,053 [saidunuhu579] [ERROR]  Error at downloading email - saidunuhu579@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 17:43:18,058 [seyiowolabi4] [ERROR]  Error at downloading email - seyiowolabi487@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 17:43:18,262 [clementidakp] [ERROR]  Error at downloading email - clementidakpo@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 17:43:18,998 [zhalilu1992@] [ERROR]  Error at downloading email - zhalilu1992@gmail.com - Traceback (most recent call last):
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 38, in _login
    server = proxy_imaplib.IMAP(
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 51, in __init__
    self.connect_proxy(proxy_host, proxy_port, proxy_type, proxy_user,
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 81, in connect_proxy
    s.connect((host, port))
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 102.223.180.213:4000: [WinError 10061] No connection could be made because the target machine actively refused it

2023-11-01 17:43:19,434 [john.snow42@] [ERROR]  Error at downloading email - john.snow42@outlook.hu - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'LOGIN failed. Account is blocked. Login to your account via a web browser to verify your identity.'

2023-11-01 17:43:26,521 [Thread-5    ] [INFO ]  Downloading finished
2023-11-01 17:43:26,521 [Thread-5    ] [INFO ]  auto_fire_responses_webhook finished
2023-11-01 17:43:27,408 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:43:27,408 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:43:27,518 [SendReport_I] [INFO ]  Webhook Inbox Thread Finished.
2023-11-01 17:48:28,244 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:48:28,245 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:53:29,090 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:53:29,090 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 17:58:29,963 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 17:58:29,964 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:03:30,819 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:03:30,820 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:08:31,689 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:08:31,690 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:13:32,539 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:13:32,540 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:18:33,366 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:18:33,366 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:23:34,213 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:23:34,214 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:28:35,037 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:28:35,038 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:33:35,865 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:33:35,865 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:38:36,727 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:38:36,728 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:43:15,506 [Thread-15   ] [INFO ]  auto_fire_responses_webhook started
2023-11-01 18:43:15,510 [SendReport_I] [INFO ]  Inbox Webhook Thread Started...
2023-11-01 18:43:17,769 [saidunuhu579] [ERROR]  Error at downloading email - saidunuhu579@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 18:43:17,924 [Thread-1    ] [INFO ]  13582
2023-11-01 18:43:18,093 [lithbello60@] [ERROR]  Error at downloading email - lithbello60@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 18:43:18,255 [clementidakp] [ERROR]  Error at downloading email - clementidakpo@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 18:43:18,276 [seyiowolabi4] [ERROR]  Error at downloading email - seyiowolabi487@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 18:43:18,976 [zhalilu1992@] [ERROR]  Error at downloading email - zhalilu1992@gmail.com - Traceback (most recent call last):
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 38, in _login
    server = proxy_imaplib.IMAP(
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 51, in __init__
    self.connect_proxy(proxy_host, proxy_port, proxy_type, proxy_user,
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 81, in connect_proxy
    s.connect((host, port))
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 102.223.180.213:4000: [WinError 10061] No connection could be made because the target machine actively refused it

2023-11-01 18:43:19,823 [john.snow42@] [ERROR]  Error at downloading email - john.snow42@outlook.hu - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'LOGIN failed. Account is blocked. Login to your account via a web browser to verify your identity.'

2023-11-01 18:43:26,518 [Thread-15   ] [INFO ]  Downloading finished
2023-11-01 18:43:26,520 [Thread-15   ] [INFO ]  auto_fire_responses_webhook finished
2023-11-01 18:43:27,517 [SendReport_I] [INFO ]  Webhook Inbox Thread Finished.
2023-11-01 18:43:37,552 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:43:37,553 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:48:38,411 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:48:38,412 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:53:39,249 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:53:39,250 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 18:58:40,082 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 18:58:40,083 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:03:40,955 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:03:40,955 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:08:41,823 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:08:41,824 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:13:42,671 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:13:42,672 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:18:43,539 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:18:43,540 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:23:44,400 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:23:44,400 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:28:45,248 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:28:45,249 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:33:46,091 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:33:46,091 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:38:46,932 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:38:46,933 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:43:15,506 [Thread-25   ] [INFO ]  auto_fire_responses_webhook started
2023-11-01 19:43:15,509 [SendReport_I] [INFO ]  Inbox Webhook Thread Started...
2023-11-01 19:43:17,816 [lithbello60@] [ERROR]  Error at downloading email - lithbello60@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 19:43:18,026 [seyiowolabi4] [ERROR]  Error at downloading email - seyiowolabi487@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 19:43:18,356 [clementidakp] [ERROR]  Error at downloading email - clementidakpo@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 19:43:18,770 [Thread-1    ] [INFO ]  13582
2023-11-01 19:43:18,793 [saidunuhu579] [ERROR]  Error at downloading email - saidunuhu579@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 19:43:19,002 [zhalilu1992@] [ERROR]  Error at downloading email - zhalilu1992@gmail.com - Traceback (most recent call last):
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 38, in _login
    server = proxy_imaplib.IMAP(
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 51, in __init__
    self.connect_proxy(proxy_host, proxy_port, proxy_type, proxy_user,
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 81, in connect_proxy
    s.connect((host, port))
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 102.223.180.213:4000: [WinError 10061] No connection could be made because the target machine actively refused it

2023-11-01 19:43:20,167 [john.snow42@] [ERROR]  Error at downloading email - john.snow42@outlook.hu - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'LOGIN failed. Account is blocked. Login to your account via a web browser to verify your identity.'

2023-11-01 19:43:25,517 [Thread-25   ] [INFO ]  Downloading finished
2023-11-01 19:43:25,518 [SendReport_I] [INFO ]  Webhook Inbox Thread Finished.
2023-11-01 19:43:25,518 [Thread-25   ] [INFO ]  auto_fire_responses_webhook finished
2023-11-01 19:43:48,796 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:43:48,797 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:48:49,651 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:48:49,652 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:53:50,515 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:53:50,515 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 19:58:51,353 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 19:58:51,355 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:03:52,226 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:03:52,227 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:08:53,066 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:08:53,069 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:13:53,900 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:13:53,901 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:18:29,112 [Thread-36   ] [INFO ]  config updated
2023-11-01 20:18:34,613 [Thread-35   ] [INFO ]  Testing Done: send to - shahimrans64@gmail.com sent_from - argentinaadriano08@gmail.com
2023-11-01 20:18:54,752 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:18:54,753 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:23:55,643 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:23:55,645 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:28:56,511 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:28:56,512 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:33:57,345 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:33:57,345 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:38:58,198 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:38:58,198 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:43:15,506 [Thread-37   ] [INFO ]  auto_fire_responses_webhook started
2023-11-01 20:43:15,511 [SendReport_I] [INFO ]  Inbox Webhook Thread Started...
2023-11-01 20:43:17,771 [saidunuhu579] [ERROR]  Error at downloading email - saidunuhu579@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 20:43:18,001 [lithbello60@] [ERROR]  Error at downloading email - lithbello60@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 20:43:18,252 [seyiowolabi4] [ERROR]  Error at downloading email - seyiowolabi487@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 20:43:18,752 [john.snow42@] [ERROR]  Error at downloading email - john.snow42@outlook.hu - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'LOGIN failed. Account is blocked. Login to your account via a web browser to verify your identity.'

2023-11-01 20:43:18,978 [zhalilu1992@] [ERROR]  Error at downloading email - zhalilu1992@gmail.com - Traceback (most recent call last):
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 38, in _login
    server = proxy_imaplib.IMAP(
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 51, in __init__
    self.connect_proxy(proxy_host, proxy_port, proxy_type, proxy_user,
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\proxy_imaplib.py", line 81, in connect_proxy
    s.connect((host, port))
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\shah_\.virtualenvs\gmail_app_old-TiubgXcJ\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 102.223.180.213:4000: [WinError 10061] No connection could be made because the target machine actively refused it

2023-11-01 20:43:19,227 [clementidakp] [ERROR]  Error at downloading email - clementidakpo@gmail.com - Traceback (most recent call last):
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap.py", line 293, in run
    imap = self._login()
  File "D:\Upwork\2020\gmail_app\gmail_app_old\gmail_app_old\imap_base.py", line 46, in _login
    server.login(self.imap_user, self.imap_pass)
  File "c:\users\shah_\.pyenv\pyenv-win\versions\3.9.0\lib\imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'

2023-11-01 20:43:19,713 [Thread-1    ] [INFO ]  13582
2023-11-01 20:43:28,521 [Thread-37   ] [INFO ]  Downloading finished
2023-11-01 20:43:28,521 [Thread-37   ] [INFO ]  auto_fire_responses_webhook finished
2023-11-01 20:43:29,520 [SendReport_I] [INFO ]  Webhook Inbox Thread Finished.
2023-11-01 20:43:54,416 [MainThread  ] [INFO ]  auto_fire_responses_webhook timer stopped
2023-11-01 20:43:59,189 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:43:59,190 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:49:00,027 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:49:00,028 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:54:00,923 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:54:00,924 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 20:59:01,785 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 20:59:01,786 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:04:02,663 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:04:02,664 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:09:03,526 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:09:03,527 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:14:04,710 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:14:04,718 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:19:05,579 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:19:05,579 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:24:07,354 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:24:07,355 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:29:09,209 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:29:09,210 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:34:10,101 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:34:10,102 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:39:10,969 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:39:10,969 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:43:20,518 [Thread-1    ] [INFO ]  13582
2023-11-01 21:44:11,901 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:44:11,902 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:49:13,806 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:49:13,807 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:54:14,692 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:54:14,692 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 21:59:15,606 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 21:59:15,607 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 22:04:16,476 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 22:04:16,476 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 22:09:17,352 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 22:09:17,352 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 22:11:58,211 [MainThread  ] [INFO ]  Exiting
2023-11-01 22:12:02,817 [MainThread  ] [INFO ]  Logger Started
2023-11-01 22:12:02,824 [MainThread  ] [INFO ]  Scheduler started
2023-11-01 22:12:02,827 [MainThread  ] [INFO ]  Logger Started
2023-11-01 22:12:02,828 [MainThread  ] [INFO ]  Scheduler started
2023-11-01 22:12:02,830 [MainThread  ] [INFO ]  gmonster_desktop_id - e86e379f-5918-412f-b903-d11e6a1b7c20
2023-11-01 22:12:02,833 [MainThread  ] [INFO ]  config updated
2023-11-01 22:12:03,634 [MainThread  ] [INFO ]  auto_fire_responses_webhook Interval: 1 hour
2023-11-01 22:12:03,635 [MainThread  ] [INFO ]  auto_fire_responses_webhook timer started
2023-11-01 22:12:04,415 [Thread-1    ] [INFO ]  13582
2023-11-01 22:12:23,609 [Thread-6    ] [INFO ]  config updated
2023-11-01 22:12:28,822 [Thread-5    ] [INFO ]  Testing Done: send to - shahimrans64@gmail.com sent_from - argentinaadriano08@gmail.com
2023-11-01 22:17:04,557 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 22:17:04,558 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 22:22:05,454 [Thread-4    ] [INFO ]  Internal Process, update_checker: campaign status - False
2023-11-01 22:22:05,455 [Thread-4    ] [INFO ]  Internal Process: No updates available.
2023-11-01 22:23:28,056 [MainThread  ] [INFO ]  Exiting
